/**
 * Schemas for opaque library-assigned job identifiers.
 */
import { Schema } from "effect"

/**
 * Nonempty branded identifier generated by the backend on first insertion.
 * Applications never supply job IDs to enqueue.
 *
 * @category schemas
 */
export const JobId = Schema.String.pipe(
  Schema.check(Schema.isMinLength(1)),
  Schema.brand("effect-jobs/JobId")
)
/**
 * Decoded value of the JobId Schema.
 *
 * @category models
 */
export type JobId = typeof JobId.Type
